# Generated by Django 3.1.6 on 2021-05-02 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QandA', '0003_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
