# Generated by Django 3.1.5 on 2021-03-06 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_user', '0001_initial'),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticeboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='some string', max_length=128, verbose_name='제목')),
                ('contents', models.TextField(default='some content', verbose_name='내용')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_user.comuser', verbose_name='작성자')),
            ],
            options={
                'verbose_name': '공지사항 게시글',
                'verbose_name_plural': '공지사항 게시글',
                'db_table': 'com_notice_board',
            },
        ),
        migrations.CreateModel(
            name='Referenceboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='some string', max_length=128, verbose_name='제목')),
                ('contents', models.TextField(default='some content', verbose_name='내용')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_user.comuser', verbose_name='작성자')),
            ],
            options={
                'verbose_name': '자료실 게시물',
                'verbose_name_plural': '자료실 게시물',
                'db_table': 'com_reference_board',
            },
        ),
        migrations.DeleteModel(
            name='Board',
        ),
    ]
