# Generated by Django 3.1.5 on 2021-03-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20210306_0716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referenceboard',
            options={'verbose_name': '자료실 게시글', 'verbose_name_plural': '자료실 게시글'},
        ),
        migrations.AddField(
            model_name='referenceboard',
            name='post_hit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
