# Generated by Django 3.1.5 on 2021-03-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20210306_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticeboard',
            name='post_hit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
